name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 24
          cache: true
          run-install: true
      - name: GQL checks
        run: |
          vpx gql-tada generate output
          vpx gql-tada check
      - name: Type check
        run: vpr check
      - name: Check
        if: ${{ !cancelled() }}
        run: vp check
      - name: Build
        if: ${{ !cancelled() }}
        run: vp build

  rust:
    name: Rust
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: src-tauri
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev pkg-config libssl-dev
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2026-08-23
          components: rustfmt, clippy
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"
      - name: Format
        run: cargo fmt --check
      - name: Clippy
        if: ${{ !cancelled() }}
        run: cargo clippy --all-targets -- -D warnings
