name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 24
          cache: true
          run-install: true
      - name: Check
        run: vp check
      - name: GQL checks
        if: ${{ !cancelled() }}
        run: |
          vpx gql-tada generate output
          vpx gql-tada check
      - name: Type check
        if: ${{ !cancelled() }}
        run: vpr check
